/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/glass.glb 
Author: Esgku (https://sketchfab.com/EsgkuBR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/glass-3be072346e3b437bb12144e31fbe7e8f
Title: Glass
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/glass.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={3.272}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.nurbsToPoly5_lambert2_0.geometry} material={materials.lambert2} position={[-6.359, 0, 15.126]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/glass.glb')
